### PR TITLE
Feature: inseert issue as markdown link

### PR DESCRIPTION
**Pull request by kyoh86**
- New feature : insert issue as Markdown link
- New map : &lt;C-l&gt;.

for: #39

### CODE REVIEW

**Comment by sbulav** [comment]
Thanks for your contribution! Looking good to me.
One small thing - please update [README](https://github.com/nvim-telescope/telescope-github.nvim/blob/master/README.md?plain=1#L104) new mapping

**Comment by kyoh86** [comment]
@sbulav thank you for your review.
I wrote the mapping on the README.md.

**Review by sbulav — APPROVED** [review]

**Comment by sbulav** [comment]
Great, one last thing:
Please apply [suggestions from StyLua](https://github.com/nvim-telescope/telescope-github.nvim/runs/6128010530?check_suite_focus=true#step:3:15)

**Comment by kyoh86** [comment]
@sbulav thanks, I did it.

**Pull request merged**
