### PR TITLE
update gh run list columns

### LINKED ISSUE #22: `gh run` requires  a gh version ≤ 1.10.3
[This line](https://github.com/nvim-telescope/telescope-github.nvim/blob/master/lua/telescope/_extensions/gh_make_entry.lua#L58) assumes the last entry in the table will be the id, but [gh 1.11.0](https://github.com/cli/cli/releases/tag/v1.11.0) added in the `elapsed` and `age` columns at the end.

Unfortunately, the columns between 1.10.3 and newer versions don't align, so the index would need to change depending on the version. 

I'm not sure what level of backwards compatibility this project hopes to maintain, so I figured I'd open an issue before submitting a patch that would require a new minimum version.

### PR DESCRIPTION
**Pull request by jacobfoard**
Fixes #22 and adds a note about the required `gh` version

### CODE REVIEW

**Comment by windwp** [comment]
sorry it is not working for me you get wrong id after that i use gh 1.12.1
 I think we don't need to get value from age or elapsed  because we don't display it on table

**Comment by jacobfoard** [comment]
I dropped the new fields, I'm also on 1.12.1, so not sure what issue you're seeing. 

```patch
diff --git a/lua/telescope/_extensions/gh_make_entry.lua b/lua/telescope/_extensions/gh_make_entry.lua
index be67b87..aba1adb 100644
--- a/lua/telescope/_extensions/gh_make_entry.lua
+++ b/lua/telescope/_extensions/gh_make_entry.lua
@@ -50,6 +50,7 @@ function gh_make_entry.gen_from_run(opts)
   return function (entry)
     if entry == '' then return nil end
     local tmp_table = vim.split(entry,"\t");
+    print(vim.inspect(tmp_table))
     local active = tmp_table[1] or ""
     local status = tmp_table[2] or ""
     local description = tmp_table[3] or ""
```

If you try that patch, which index are you seeing the id field in?

**Comment by sbulav** [comment]
I am using gh version 1.12.1 (2021-07-01), and for me `local id = tmp_table[7] or ""` is working fine.
BTW, we can do something like this to support both versions:
```lua
    local id = ""
    if #tmp_table > 8 then 
        id = tmp_table[7]
    else
        id = tmp_table[#tmp_table]
    end
```

**Comment by jacobfoard** [comment]
An elegant solution @sbulav, much better than what I was thinking for parsing version numbers. I've pushed that fix.

**Pull request merged**
